---
title: "Data Wrangling 1 _ Data Manipulation"
author: "Jiayi Shen"
date: "9/20/2018"
output: html_document
---

```{r, include = FALSE}
#knitr::opts_chunk$set
library(tidyverse)
```

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```


## Select variables

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```


... by specifying a range:
```{r}
select(litters_data, group:gd_of_birth)
select(litters_data, group, gd_of_birth:pups_survive)
```


... by saing what you want to remove:
```{r}
select(litters_data, -litter_number)
```

select and rename in the same process:
```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
rename(litters_data, LiTtEr_NuMbEr = litter_number)
```

... use select helpers:
```{r}
select(litters_data, starts_with("gd"))
select(litters_data, litter_number, starts_with("pup"))

# moving one coloum to the left and everything else follows.
select(litters_data, litter_number, everything())
```

in-class assessment 1:
```{r}
select(pups_data, litter_number, sex, pd_ears)
```



## Filter

```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)
filter(litters_data, pups_born_alive == 8)

filter(litters_data, is.na(gd0_weight))
filter(litters_data, !is.na(gd0_weight))

# using the "|"(or) operator
filter(litters_data, group == "Low8" | group == "Low7")


filter(litters_data, pups_born_alive %in% 4:6)
filter(litters_data, pups_born_alive %in% 4:6, !is.na(gd0_weight))
filter(litters_data, pups_born_alive %in% 4:6 & !is.na(gd0_weight))
```

in-class assessment 2:
```{r}
filter(pups_data, sex == 1)
filter(pups_data, pd_walk < 11, sex == 2)
```

## Mutate
