---
title: "data_wrangling_i"
author: "Jiayi Shen"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


## import FAS csv files

import my first csv. 


```{r read_data}
litters_data = read_csv(file = "./data/FAS_litters.csv")
names(litters_data)

litters_data = janitor::clean_names(litters_data)
names(litters_data)

#litters_data = read_csv(file = "./data/FAS_litters.csv",
#  skip = 10, col_names = FALSE)
```



## csv files assessments

```{r import_pups_data}
pups_data = read_csv(file = "./data/FAS_pups.csv", col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
skimr::skim(litters_data)
```


In the console panel, can use 'View(litters_data)' command to view the current data file. Alternatively, click on the data in the "Environment" tab on the right panel.
\

## Other data file formats
For example, Excel\

```{r read_excel_files}
library(readxl)
mlb11_data = readxl::read_excel("./data/mlb11.xlsx", n_max = 20)
mlb11_selected = readxl::read_excel("./data/mlb11.xlsx", range = "A1:E17")
head(mlb11_data, 5)
```

Then, SAS
```{r read_SAS_files}
library(haven)
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```


## Compare with base R
```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")

pups_base
### prints out all lines
pups_readr
### prints out first few lines

```

